// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: app/sdk/proto/mlog/logs.proto

package mlog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem para registrar um novo log
type NewLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewLog) Reset() {
	*x = NewLog{}
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLog) ProtoMessage() {}

func (x *NewLog) ProtoReflect() protoreflect.Message {
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLog.ProtoReflect.Descriptor instead.
func (*NewLog) Descriptor() ([]byte, []int) {
	return file_app_sdk_proto_mlog_logs_proto_rawDescGZIP(), []int{0}
}

func (x *NewLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NewLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *NewLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NewLog) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Resposta ao registrar um log
type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_app_sdk_proto_mlog_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Mensagem com os logs retornados
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_app_sdk_proto_mlog_logs_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Log) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Coleção de logs
type Logs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logs) Reset() {
	*x = Logs{}
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logs) ProtoMessage() {}

func (x *Logs) ProtoReflect() protoreflect.Message {
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logs.ProtoReflect.Descriptor instead.
func (*Logs) Descriptor() ([]byte, []int) {
	return file_app_sdk_proto_mlog_logs_proto_rawDescGZIP(), []int{3}
}

func (x *Logs) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Logs) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Logs) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Consulta para buscar logs
type SearchQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	AsFile        bool                   `protobuf:"varint,6,opt,name=as_file,json=asFile,proto3" json:"as_file,omitempty"` // Se true, retorna como arquivo ao invés de stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_app_sdk_proto_mlog_logs_proto_rawDescGZIP(), []int{4}
}

func (x *SearchQuery) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SearchQuery) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SearchQuery) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SearchQuery) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchQuery) GetAsFile() bool {
	if x != nil {
		return x.AsFile
	}
	return false
}

// Resposta quando os logs são retornados como arquivo
type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Compression   string                 `protobuf:"bytes,3,opt,name=compression,proto3" json:"compression,omitempty"` // Tipo de compressão utilizada
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_sdk_proto_mlog_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_app_sdk_proto_mlog_logs_proto_rawDescGZIP(), []int{5}
}

func (x *FileResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *FileResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileResponse) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

var File_app_sdk_proto_mlog_logs_proto protoreflect.FileDescriptor

const file_app_sdk_proto_mlog_logs_proto_rawDesc = "" +
	"\n" +
	"\x1dapp/sdk/proto/mlog/logs.proto\x12\x04logs\"\xcb\x01\n" +
	"\x06NewLog\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x126\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1a.logs.NewLog.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xd5\x01\n" +
	"\x03Log\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x123\n" +
	"\bmetadata\x18\x05 \x03(\v2\x17.logs.Log.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x04Logs\x12\x1d\n" +
	"\x04logs\x18\x01 \x03(\v2\t.logs.LogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xa7\x01\n" +
	"\vSearchQuery\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x17\n" +
	"\aas_file\x18\x06 \x01(\bR\x06asFile\"h\n" +
	"\fFileResponse\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12 \n" +
	"\vcompression\x18\x03 \x01(\tR\vcompression28\n" +
	"\tLogWriter\x12+\n" +
	"\bRegister\x12\f.logs.NewLog\x1a\x11.logs.LogResponse2\x9a\x01\n" +
	"\tLogReader\x12'\n" +
	"\x06Search\x12\x11.logs.SearchQuery\x1a\n" +
	".logs.Logs\x125\n" +
	"\fExportToFile\x12\x11.logs.SearchQuery\x1a\x12.logs.FileResponse\x12-\n" +
	"\n" +
	"StreamFile\x12\x11.logs.SearchQuery\x1a\n" +
	".logs.Logs0\x01B\x14Z\x12app/sdk/proto/mlogb\x06proto3"

var (
	file_app_sdk_proto_mlog_logs_proto_rawDescOnce sync.Once
	file_app_sdk_proto_mlog_logs_proto_rawDescData []byte
)

func file_app_sdk_proto_mlog_logs_proto_rawDescGZIP() []byte {
	file_app_sdk_proto_mlog_logs_proto_rawDescOnce.Do(func() {
		file_app_sdk_proto_mlog_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_sdk_proto_mlog_logs_proto_rawDesc), len(file_app_sdk_proto_mlog_logs_proto_rawDesc)))
	})
	return file_app_sdk_proto_mlog_logs_proto_rawDescData
}

var file_app_sdk_proto_mlog_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_sdk_proto_mlog_logs_proto_goTypes = []any{
	(*NewLog)(nil),       // 0: logs.NewLog
	(*LogResponse)(nil),  // 1: logs.LogResponse
	(*Log)(nil),          // 2: logs.Log
	(*Logs)(nil),         // 3: logs.Logs
	(*SearchQuery)(nil),  // 4: logs.SearchQuery
	(*FileResponse)(nil), // 5: logs.FileResponse
	nil,                  // 6: logs.NewLog.MetadataEntry
	nil,                  // 7: logs.Log.MetadataEntry
}
var file_app_sdk_proto_mlog_logs_proto_depIdxs = []int32{
	6, // 0: logs.NewLog.metadata:type_name -> logs.NewLog.MetadataEntry
	7, // 1: logs.Log.metadata:type_name -> logs.Log.MetadataEntry
	2, // 2: logs.Logs.logs:type_name -> logs.Log
	0, // 3: logs.LogWriter.Register:input_type -> logs.NewLog
	4, // 4: logs.LogReader.Search:input_type -> logs.SearchQuery
	4, // 5: logs.LogReader.ExportToFile:input_type -> logs.SearchQuery
	4, // 6: logs.LogReader.StreamFile:input_type -> logs.SearchQuery
	1, // 7: logs.LogWriter.Register:output_type -> logs.LogResponse
	3, // 8: logs.LogReader.Search:output_type -> logs.Logs
	5, // 9: logs.LogReader.ExportToFile:output_type -> logs.FileResponse
	3, // 10: logs.LogReader.StreamFile:output_type -> logs.Logs
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_sdk_proto_mlog_logs_proto_init() }
func file_app_sdk_proto_mlog_logs_proto_init() {
	if File_app_sdk_proto_mlog_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_sdk_proto_mlog_logs_proto_rawDesc), len(file_app_sdk_proto_mlog_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_app_sdk_proto_mlog_logs_proto_goTypes,
		DependencyIndexes: file_app_sdk_proto_mlog_logs_proto_depIdxs,
		MessageInfos:      file_app_sdk_proto_mlog_logs_proto_msgTypes,
	}.Build()
	File_app_sdk_proto_mlog_logs_proto = out.File
	file_app_sdk_proto_mlog_logs_proto_goTypes = nil
	file_app_sdk_proto_mlog_logs_proto_depIdxs = nil
}
